//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using TwitchPointsAuction.Classes;
using TwitchPointsAuction.Models;

namespace TwitchPointsAuction.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    public partial class UserSettings : global::System.Configuration.ApplicationSettingsBase {

        private static UserSettings defaultInstance = ((UserSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new UserSettings())));

        public static UserSettings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public IrcChatSettings TwitchIrcSettings
        {
            get
            {
                return ((IrcChatSettings)(this["TwitchIrcSettings"]));
            }
            set
            {
                this["TwitchIrcSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public PubSubSettings TwitchPubSubSettings
        {
            get
            {
                return ((PubSubSettings)(this["TwitchPubSubSettings"]));
            }
            set
            {
                this["TwitchPubSubSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public AuctionSettingsModel DefaultAuctionSettings
        {
            get
            {
                return ((AuctionSettingsModel)(this["DefaultAuctionSettings"]));
            }
            set
            {
                this["DefaultAuctionSettings"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public AuctionRulesModel DefaultAuctionRules
        {
            get
            {
                return ((AuctionRulesModel)(this["DefaultAuctionRules"]));
            }
            set
            {
                this["DefaultAuctionRules"] = value;
            }
        }
    }
}
